title: Adam Lauz
logo: https://avatars.githubusercontent.com/u/2620814?v=4
description: ML | AI | adamlauz@gmail.com
author :
	  name : Name Lastname
	  email : blah@email.test
	  github : username
	  twitter : username
	  feedburner : feedname
theme: jekyll-theme-minimal
