title: Adam Lauz
logo: https://avatars.githubusercontent.com/u/2620814?v=4
description: adamlauz@gmail.com
author:
  name: Adam Lauz
  email: "adamlauz@gmail.com"
remote_theme: pages-themes/cayman@v0.2.0
