page.title: Adam Lauz
logo: https://avatars.githubusercontent.com/u/2620814?v=4
description: adamlauz@gmail.com
theme: minimal-mistakes-jekyll
author:
  name: Adam Lauz
  email: "adamlauz@gmail.com"

