title: Adam Lauz
logo: https://avatars.githubusercontent.com/u/2620814?v=4
description: ML | AI | 
theme: jekyll-theme-so-simple
author :
  name : Adam Lauz
  email : adamlauz@gmail.com
  github : AdamLauz
  linkedin : https://www.linkedin.com/in/adam-l-2b96985b/
