title: Adam Lauz
logo: https://avatars.githubusercontent.com/u/2620814?v=4
description: ML | AI | 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

author:
  name: Adam Lauz
  email: "adamlauz@gmail.com"
