title: Adam Lauz
logo: https://avatars.githubusercontent.com/u/2620814?v=4
description: ML | AI
mail: adamlauz@gmail.com
linkedin: https://www.linkedin.com/in/adam-l-2b96985b/
theme: jekyll-theme-minimal
