title: Adam Lauz
logo: https://avatars.githubusercontent.com/u/2620814?v=4
description: ML | AI | adamlauz@gmail.com
email: adamlauz@gmail.com
url: https://www.linkedin.com/in/adam-l-2b96985b/
theme: jekyll-theme-minimal
